Course.find_or_create_by(name: "Alpine Golf",alphabet: "A")
Course.find_or_create_by(name: "Amata Spring Golf",alphabet: "A")
Course.find_or_create_by(name: "Ayutthaya Golf",alphabet: "A")
Course.find_or_create_by(name: "Thai Country",alphabet: "T")
Course.find_or_create_by(name: "Vintage Club",alphabet: "V")
Course.find_or_create_by(name: "Siam Country(Old)",alphabet: "S")
Course.find_or_create_by(name: "Siam Country(Plantation)",alphabet: "S")
Course.find_or_create_by(name: "Siam Country(WaterSide)",alphabet: "S")
Course.find_or_create_by(name: "The Pine & Lodge",alphabet: "T")
Course.find_or_create_by(name: "Royal Lake Side",alphabet: "R")
Course.find_or_create_by(name: "Windsor Park Golf",alphabet: "W")
Course.find_or_create_by(name: "Cascata Golf",alphabet: "C")
Course.find_or_create_by(name: "Kiarti Thanee Country",alphabet: "K")
Course.find_or_create_by(name: "Green Valley Country",alphabet: "G")
Course.find_or_create_by(name: "Krung Kavee Golf",alphabet: "K")
Course.find_or_create_by(name: "Krungthep Kreetha Golf",alphabet: "K")
Course.find_or_create_by(name: "Summit Windmill",alphabet: "S")
Course.find_or_create_by(name: "Subhapruek Golf",alphabet: "S")
Course.find_or_create_by(name: "Swan Golf Country",alphabet: "S")
Course.find_or_create_by(name: "Thana City Golf",alphabet: "T")
Course.find_or_create_by(name: "Thanon Golf",alphabet: "T")
Course.find_or_create_by(name: "Subhapruek Golf",alphabet: "S")
Course.find_or_create_by(name: "Thanya Golf",alphabet: "T")
Course.find_or_create_by(name: "Flora Ville Golf",alphabet: "F")
Course.find_or_create_by(name: "Navatanee Golf",alphabet: "N")
Course.find_or_create_by(name: "Northern Rangsit",alphabet: "N")
Course.find_or_create_by(name: "Pinehurst Golf",alphabet: "P")
Course.find_or_create_by(name: "Bangkok Golf",alphabet: "B")
Course.find_or_create_by(name: "Bangpakong Riverside",alphabet: "B")
Course.find_or_create_by(name: "Bangpoo Golf",alphabet: "B")
Course.find_or_create_by(name: "Panyaindora Golf",alphabet: "P")
Course.find_or_create_by(name: "Best Ocean",alphabet: "B")
Course.find_or_create_by(name: "Muang Kaew Golf",alphabet: "M")
Course.find_or_create_by(name: "Unico Grande Golf",alphabet: "U")
Course.find_or_create_by(name: "Uniland Golf",alphabet: "U")
Course.find_or_create_by(name: "Ratchakram Golf",alphabet: "R")
Course.find_or_create_by(name: "Riverdale Golf",alphabet: "R")
Course.find_or_create_by(name: "Lakewood Golf",alphabet: "L")
Course.find_or_create_by(name: "Legacy Golf",alphabet: "L")
Course.find_or_create_by(name: "Royal Golf",alphabet: "R")
Course.find_or_create_by(name: "Royal Gems Golf",alphabet: "R")
Course.find_or_create_by(name: "Royal Gems Golf City",alphabet: "R")
Course.find_or_create_by(name: "Rose Garden",alphabet: "R")
Course.find_or_create_by(name: "Lotus Valley",alphabet: "L")

Course.find_or_create_by(name: "Khao Kheow Country",alphabet: "K")
Course.find_or_create_by(name: "Green Wood Golf",alphabet: "G")
Course.find_or_create_by(name: "St.Andrews2000 Golf",alphabet: "S")
Course.find_or_create_by(name: "Patana Golf",alphabet: "P")
Course.find_or_create_by(name: "Pattaya Country",alphabet: "P")
Course.find_or_create_by(name: "Bangpra Golf",alphabet: "B")
Course.find_or_create_by(name: "Wangjuntr Golf Park",alphabet: "W")
Course.find_or_create_by(name: "Phoenix Golf",alphabet: "P")
Course.find_or_create_by(name: "Burapha Golf",alphabet: "B")
Course.find_or_create_by(name: "Pleasant Valley Golf",alphabet: "P")
Course.find_or_create_by(name: "Chrystal Bay Golf",alphabet: "C")
Course.find_or_create_by(name: "Mountain Shadow Golf",alphabet: "M")
Course.find_or_create_by(name: "Rayong Green Valley",alphabet: "R")
Course.find_or_create_by(name: "Leamchabang Country",alphabet: "L")
Course.find_or_create_by(name: "Bangsai Country Club",alphabet: "B")
Course.find_or_create_by(name: "Muang Ake Golf",alphabet: "M")
Course.find_or_create_by(name: "Muang Ake Vista Golf",alphabet: "M")
Course.find_or_create_by(name: "Army Sport CenterⅡ",alphabet: "A")
Course.find_or_create_by(name: "Black Mountain",alphabet: "B")
Course.find_or_create_by(name: "Banyan Golf Club",alphabet: "B")
Course.find_or_create_by(name: "Dhanarat Golf Club",alphabet: "D")
Course.find_or_create_by(name: "Eagle Milford Golf Course",alphabet: "E")
Course.find_or_create_by(name: "Royal Hua Hin Golf Course",alphabet: "R")
Course.find_or_create_by(name: "NCR Country",alphabet: "N")
Course.find_or_create_by(name: "Nikanti Golf Club",alphabet: "N")
Course.find_or_create_by(name: "Parichat Golf Links",alphabet: "P")
Course.find_or_create_by(name: "Singha Park Khonkaen Golf",alphabet: "S")
Course.find_or_create_by(name: "Watermill Golf",alphabet: "W")
Course.find_or_create_by(name: "Khao Cha-Ngok Golf",alphabet: "K")
Course.find_or_create_by(name: "Artitaya Golf ",alphabet: "A")
Course.find_or_create_by(name: "Lakewood Links ",alphabet: "L")
		



Category.find_or_create_by(score_range: "under 69",color: "primary")
Category.find_or_create_by(score_range: "70-79",color: "success")
Category.find_or_create_by(score_range: "80-89",color: "info")
Category.find_or_create_by(score_range: "90-99",color: "warning")
Category.find_or_create_by(score_range: "over 100",color: "default")